### PR TITLE
Apply Choco Best Practices

### PR DESCRIPTION
**Pull request by gep13**
As per suggestion in #15

### CODE REVIEW

**Comment by crutkas** [comment]
Love this. Maybe we should have a page that lists best practices. Where did you find the choco best practices?

**Comment by yodurr** [comment]
I don't see any "' vs '" inconsistencies any more, would like to merge this to master.  Objections?

**Comment by gep13** [comment]
I think we have most of these mentioned in places across the website, but not in one complete list.  Perhaps that is something that we need to add?

They are summarised in the issue that @ferventcoder created here: https://github.com/Microsoft/windows-dev-box-setup-scripts/issues/15 but I will try to get a page created on chocolatey.org that we can also point people at.

**Comment by gep13** [comment]
@crutkas I am not seeing the inconsistency that you refer to.  Can you point me to it, or comment on the line in question in the PR and I can get it fixed.  Thanks.

**Comment by crutkas** [comment]
Clearly My eyes need checking as I could have swore I saw the quote vs tick flipped.

**Comment by gep13** [comment]
@crutkas @yodurr are we good to get this merged?

**Comment by gep13** [comment]
@yodurr thanks for merging!

**Pull request merged**
